### ISSUE TITLE
Can't run as root

### ISSUE THREAD

**Issue by bendonderer** [das-kaesebrot/wg-interactive#5]
It seems that this tool can't be run under the user "root": _You need to execute this program as root_

Presumably because root is not a sudo member:
https://github.com/das-kaesebrot/wg-interactive/blob/main/wg-interactive.py#L369

The environment variable `SUDO_UID` does not exist, but maybe another check for the variable `USER=root` could fix this.

**Comment by das-kaesebrot** [comment]
Thank you, commit d6f628d addresses this issue.
